spring:
  application:
    name: ajouchong
  config:
    import: optional:file:./.env
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  profiles:
    active: prod
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    open-in-view: false
  sql:
    init:
      mode: always
  web:
    resources:
      static-locations: file:/home/ubuntu/ajouchong/img/

server:
  port: 8080
